---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-static-dynamic
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc-dynamic
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: efs-static-dynamic-pod
spec:
  containers:
    - name: app
      image: centos
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo $(date -u) >> /data/out; sleep 5; done"]
      volumeMounts:
        - name: persistent-storage
          mountPath: /data
        - name: static-pv
          mountPath: /opt
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: efs-static-dynamic
    - name: static-pv
      persistentVolumeClaim:
        claimName: efs-claim-static
