apiVersion: v1
kind: Pod
metadata:
  name: app1
spec:
  containers:
  - name: app1
    image: nginx
#    command: ["/bin/sh"]
#    args: ["-c", "while true; do echo $(date -u) >> /data/out1.txt; sleep 5; done"]
    volumeMounts:
    - name: persistent-storage
      mountPath: /tmp
  volumes:
  - name: persistent-storage
    persistentVolumeClaim:
      claimName: efs-claim-static
